version: "3.13"
services:
  db-medical_records:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - src/.env
    ports:
      - "5435:5432"
    networks:
      - mc_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  web-medical-records:
    build: .
    command: /app/start.sh
    volumes:
      - ./src:/app/src
    ports:
      - "8300:8300"
    networks:
      - mc_network
    depends_on:
      db-medical_records:
        condition: service_healthy
networks:
  mc_network:
    external: true